/**
 * EXPAND.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObjectId { 
    readonly timestamp?: number;
    /** @deprecated */
    readonly machine?: number;
    /** @deprecated */
    readonly pid?: number;
    /** @deprecated */
    readonly increment?: number;
    readonly creationTime?: string;
}

