/**
 * EXPAND.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum PlanetStatus {
    ToDo = 0,
    EnRoute = 1,
    OK = 2,
    Not_OK = 3
}

